export type CefrLevel = "A1" | "A2" | "B1" | "B2" | "C1";

export type LessonCategory =
  | "日常交流"
  | "工作学习"
  | "旅行出行"
  | "观点表达"
  | "地道口语";

export type Lesson = {
  id: number;
  level: CefrLevel;
  phrase: string;
  ipa: string;
  meaning: string;
  example: string;
  translation: string;
  note: string;
  category: LessonCategory;
};

export const LEVELS: CefrLevel[] = ["A1", "A2", "B1", "B2", "C1"];

export const CATEGORIES: LessonCategory[] = [
  "日常交流",
  "工作学习",
  "旅行出行",
  "观点表达",
  "地道口语",
];

export const LESSONS: Lesson[] = [
  {
    id: 1,
    level: "A1",
    phrase: "Sounds good.",
    ipa: "/saʊndz ɡʊd/",
    meaning: "听起来不错；就这么办。",
    example: "Let's meet at the station at eight. — Sounds good.",
    translation: "我们八点在车站见。——好啊。",
    note: "比 OK 更自然，常用来接受建议或安排。",
    category: "日常交流",
  },
  {
    id: 2,
    level: "A1",
    phrase: "Take care.",
    ipa: "/teɪk ker/",
    meaning: "保重；路上小心。",
    example: "It was great seeing you. Take care!",
    translation: "很高兴见到你。保重！",
    note: "告别时使用，语气比 goodbye 更温暖。",
    category: "日常交流",
  },
  {
    id: 3,
    level: "A1",
    phrase: "I'm on my way.",
    ipa: "/aɪm ɑːn maɪ weɪ/",
    meaning: "我正在路上。",
    example: "Don't worry. I'm on my way and I'll be there soon.",
    translation: "别担心，我已经在路上了，很快就到。",
    note: "也可说 on the way，但说明自己正在赶来时通常用 my。",
    category: "旅行出行",
  },
  {
    id: 4,
    level: "A1",
    phrase: "Could you help me?",
    ipa: "/kʊd juː help miː/",
    meaning: "你能帮我一下吗？",
    example: "Could you help me find this address?",
    translation: "你能帮我找一下这个地址吗？",
    note: "Could you… 比 Can you… 更客气。",
    category: "旅行出行",
  },
  {
    id: 5,
    level: "A1",
    phrase: "It depends.",
    ipa: "/ɪt dɪˈpendz/",
    meaning: "看情况。",
    example: "Are you free this weekend? — It depends on my schedule.",
    translation: "你这周末有空吗？——要看我的安排。",
    note: "后面常接 on + 条件。",
    category: "观点表达",
  },
  {
    id: 6,
    level: "A2",
    phrase: "No worries.",
    ipa: "/noʊ ˈwɝːiz/",
    meaning: "没关系；不用担心。",
    example: "Sorry I'm late. — No worries. We just got here.",
    translation: "抱歉我迟到了。——没事，我们也刚到。",
    note: "可回应道歉，也可表示“这件事包在我身上”。",
    category: "日常交流",
  },
  {
    id: 7,
    level: "A2",
    phrase: "How come?",
    ipa: "/haʊ kʌm/",
    meaning: "怎么会？为什么？",
    example: "I'm not going tonight. — How come?",
    translation: "我今晚不去了。——为什么？",
    note: "口语疑问句，后面接陈述语序：How come you left?",
    category: "地道口语",
  },
  {
    id: 8,
    level: "A2",
    phrase: "By the way,",
    ipa: "/baɪ ðə weɪ/",
    meaning: "顺便说一下。",
    example: "By the way, have you booked the hotel yet?",
    translation: "顺便问一下，你订酒店了吗？",
    note: "用于自然切换到相关或附带话题。",
    category: "日常交流",
  },
  {
    id: 9,
    level: "A2",
    phrase: "Give me a hand.",
    ipa: "/ɡɪv miː ə hænd/",
    meaning: "帮我一把。",
    example: "Could you give me a hand with these boxes?",
    translation: "你能帮我搬一下这些箱子吗？",
    note: "常搭配 with + 事情；不是“把手给我”。",
    category: "日常交流",
  },
  {
    id: 10,
    level: "A2",
    phrase: "Make sure…",
    ipa: "/meɪk ʃʊr/",
    meaning: "务必；确认。",
    example: "Make sure you save a copy before closing the file.",
    translation: "关闭文件前一定要保存一份。",
    note: "后接完整句，常用于提醒重要步骤。",
    category: "工作学习",
  },
  {
    id: 11,
    level: "A2",
    phrase: "I didn't catch that.",
    ipa: "/aɪ ˈdɪdnt kætʃ ðæt/",
    meaning: "我没听清。",
    example: "Sorry, I didn't catch that. Could you say it again?",
    translation: "抱歉，我没听清。你能再说一遍吗？",
    note: "比 What? 更礼貌，适合真实交流。",
    category: "日常交流",
  },
  {
    id: 12,
    level: "B1",
    phrase: "Figure it out.",
    ipa: "/ˈfɪɡjər ɪt aʊt/",
    meaning: "弄明白；想出办法。",
    example: "Give me a few minutes. I'll figure it out.",
    translation: "给我几分钟，我会想出办法的。",
    note: "宾语是代词时必须放中间：figure it out。",
    category: "工作学习",
  },
  {
    id: 13,
    level: "B1",
    phrase: "Work out.",
    ipa: "/wɝːk aʊt/",
    meaning: "顺利解决；锻炼；算出。",
    example: "We had a few problems, but everything worked out.",
    translation: "我们遇到了一些问题，但最后都解决了。",
    note: "具体含义由语境决定；这里表示“得到好结果”。",
    category: "地道口语",
  },
  {
    id: 14,
    level: "B1",
    phrase: "Run into someone.",
    ipa: "/rʌn ˈɪntuː/",
    meaning: "偶遇某人。",
    example: "I ran into an old classmate at the airport.",
    translation: "我在机场偶遇了一位老同学。",
    note: "run into 也可表示“遇到问题”。",
    category: "日常交流",
  },
  {
    id: 15,
    level: "B1",
    phrase: "Keep that in mind.",
    ipa: "/kiːp ðæt ɪn maɪnd/",
    meaning: "记住这一点。",
    example: "The last train leaves at midnight, so keep that in mind.",
    translation: "末班车午夜发车，所以要记住这一点。",
    note: "强调某条信息会影响之后的判断。",
    category: "旅行出行",
  },
  {
    id: 16,
    level: "B1",
    phrase: "Be supposed to…",
    ipa: "/bi səˈpoʊzd tuː/",
    meaning: "应该；按规定要。",
    example: "We're supposed to submit the report by Friday.",
    translation: "按要求我们要在周五前提交报告。",
    note: "强调约定、规则或预期，不等同于强烈义务 must。",
    category: "工作学习",
  },
  {
    id: 17,
    level: "B1",
    phrase: "Go over something.",
    ipa: "/ɡoʊ ˈoʊvər/",
    meaning: "检查；复习；仔细讨论。",
    example: "Let's go over the main points one more time.",
    translation: "我们再过一遍要点吧。",
    note: "适用于材料、计划、答案和会议要点。",
    category: "工作学习",
  },
  {
    id: 18,
    level: "B1",
    phrase: "It turned out that…",
    ipa: "/ɪt tɝːnd aʊt ðæt/",
    meaning: "结果发现；原来。",
    example: "It turned out that we had met before.",
    translation: "结果发现我们以前见过。",
    note: "用于揭示与最初预期不同的结果。",
    category: "观点表达",
  },
  {
    id: 19,
    level: "B2",
    phrase: "Get the hang of it.",
    ipa: "/ɡet ðə hæŋ əv ɪt/",
    meaning: "掌握窍门；逐渐上手。",
    example: "The software feels complex, but you'll get the hang of it.",
    translation: "这个软件看起来复杂，但你会慢慢上手的。",
    note: "常用来鼓励正在学习新技能的人。",
    category: "工作学习",
  },
  {
    id: 20,
    level: "B2",
    phrase: "Be on the same page.",
    ipa: "/bi ɑːn ðə seɪm peɪdʒ/",
    meaning: "达成共识；理解一致。",
    example: "Before we start, let's make sure we're on the same page.",
    translation: "开始前，我们先确认大家理解一致。",
    note: "工作会议高频表达，不是字面上的“同一页”。",
    category: "工作学习",
  },
  {
    id: 21,
    level: "B2",
    phrase: "It's a long shot.",
    ipa: "/ɪts ə lɔːŋ ʃɑːt/",
    meaning: "成功希望不大；姑且一试。",
    example: "It's a long shot, but we might still get tickets.",
    translation: "希望不大，但我们也许还能买到票。",
    note: "表示概率低，但并非完全不可能。",
    category: "观点表达",
  },
  {
    id: 22,
    level: "B2",
    phrase: "A rule of thumb",
    ipa: "/ə ruːl əv θʌm/",
    meaning: "经验法则；实用原则。",
    example: "As a rule of thumb, arrive at the airport two hours early.",
    translation: "经验上，最好提前两小时到机场。",
    note: "表示基于经验、并非绝对精确的做法。",
    category: "旅行出行",
  },
  {
    id: 23,
    level: "B2",
    phrase: "In the long run",
    ipa: "/ɪn ðə lɔːŋ rʌn/",
    meaning: "从长远来看。",
    example: "Learning a little every day pays off in the long run.",
    translation: "每天学一点，从长远来看会有回报。",
    note: "常放在句首或句尾，用于讨论长期影响。",
    category: "观点表达",
  },
  {
    id: 24,
    level: "B2",
    phrase: "Draw the line.",
    ipa: "/drɔː ðə laɪn/",
    meaning: "划定底线。",
    example: "I can work late occasionally, but I draw the line at weekends.",
    translation: "我偶尔可以加班，但周末是我的底线。",
    note: "后面常接 at，说明不可接受的界限。",
    category: "观点表达",
  },
  {
    id: 25,
    level: "B2",
    phrase: "Come across as…",
    ipa: "/kʌm əˈkrɔːs æz/",
    meaning: "给人……的印象。",
    example: "She comes across as confident without sounding arrogant.",
    translation: "她给人很自信的感觉，但并不傲慢。",
    note: "描述别人接收到的印象，不一定是本人真实意图。",
    category: "观点表达",
  },
  {
    id: 26,
    level: "C1",
    phrase: "In hindsight,",
    ipa: "/ɪn ˈhaɪndsaɪt/",
    meaning: "事后看来。",
    example: "In hindsight, we should have tested the idea earlier.",
    translation: "事后看来，我们本应该更早验证这个想法。",
    note: "常与 should have done 连用，反思过去的决定。",
    category: "观点表达",
  },
  {
    id: 27,
    level: "C1",
    phrase: "Read between the lines.",
    ipa: "/riːd bɪˈtwiːn ðə laɪnz/",
    meaning: "读懂言外之意。",
    example: "If you read between the lines, the email is actually a warning.",
    translation: "如果读懂言外之意，这封邮件其实是在警告。",
    note: "用于分析没有被直接说出的态度或意图。",
    category: "观点表达",
  },
  {
    id: 28,
    level: "C1",
    phrase: "Hit the ground running.",
    ipa: "/hɪt ðə ɡraʊnd ˈrʌnɪŋ/",
    meaning: "迅速进入状态。",
    example: "The new manager hit the ground running in her first week.",
    translation: "新经理第一周就迅速进入了状态。",
    note: "强调没有漫长适应期，一开始就高效行动。",
    category: "工作学习",
  },
  {
    id: 29,
    level: "C1",
    phrase: "Take it with a grain of salt.",
    ipa: "/teɪk ɪt wɪð ə ɡreɪn əv sɔːlt/",
    meaning: "对其持保留态度。",
    example: "Online reviews can help, but take them with a grain of salt.",
    translation: "网上评价会有帮助，但也要持保留态度。",
    note: "表示信息可能不完全可靠，不要照单全收。",
    category: "地道口语",
  },
  {
    id: 30,
    level: "C1",
    phrase: "The ball is in your court.",
    ipa: "/ðə bɔːl ɪz ɪn jʊr kɔːrt/",
    meaning: "下一步由你决定。",
    example: "I've shared the proposal. The ball is in your court now.",
    translation: "我已经发了方案，现在该你决定下一步了。",
    note: "来自网球，比喻责任或决定权已经转到对方。",
    category: "工作学习",
  },
];
